### ISSUE TITLE
Recommended papers not showing

### ISSUE THREAD

**Issue by danielegrattarola** [karpathy/arxiv-sanity-preserver#120]
Hi, 
the recommendation section of my profile is stuck at Oct. 4th, and i don't see any paper more recent than that. 
I have added several papers to the library after Oct. 4th, and I'm sure that new papers came out on Arxiv that should have been caught by the recommender. 
Is there any way I can troubleshoot this??

Thanks, 
Daniele

**Comment by karelin** [comment]
As far as I can see, the project stalled after Dr. Karpathy joined Tesla as Head of AI. For some time, it got updates of data, but not fixes, etc. Perhaps, it is necessary to start an official fork.

**Comment by karpathy** [comment]
I'm sorry guys, I found the issue (update jobs were killed due to too much memory use on my node), scaled up the instance and am recomputing all of the recommendations. They should be updated in a few hours.

Separately, I still maintain arxiv-sanity and have a recurring dream of taking a good weekend to focus on it and put it in a better shape.

**Comment by danielegrattarola** [comment]
Works perfectly now, thank you so much.

**Comment by m-legrand** [comment]
Same problem is appearing for me now (recently created account).

**Comment by karpathy** [comment]
fixing, should be good in ~day
